# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Data Science For Struggling Stats Students
email: rmiles7720@gmail.com 
description: >- 
#Finding somewhere where I can learn about coding and data mining/engineering simply has always been rather hard for me, so hopefully I can share some of my knowledge to help other students that feel a bit in over their heads! 
baseurl: "/stat386-projects" # keep this the same or change it to the name of the repository 
url: "https://rmiles7720.github.io" #  change this to "https://<your-github-username>.github.io"
image: "assets/images/image5.jpg"
author: Rachel Miles
copyright: RCM 

# Social media users names.  Leave fields blank that you don't want displayed
github_username:  rmiles7720
#linkedin_username: 386student
#instagram_username: 


# Build settings
# removed minima theme to a regular theme
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
